# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

def shared_pods
    
end

target 'Weather Forecaster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather Forecaster
  shared_pods

  target 'Weather ForecasterTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
    pod 'OHHTTPStubs/Swift'
  end

  target 'Weather ForecasterUITests' do
    # Pods for testing
  end

end
